import type { AnalysisResult } from '../../types/analysis-result.js';
import type { RenderMeta } from './render-html.js';

export function renderMarkdownReport(result: AnalysisResult, meta: RenderMeta): string {
  const reachable = result.results.filter((v) => v.is_reachable);
  const notReachable = result.results.filter((v) => !v.is_reachable);

  let md = `# VRA - Vulnerability Reachability Analysis Report\n\n`;

  if (meta.aiPowered && meta.providerName) {
    md += `_Powered by ${meta.providerName}_\n\n`;
  }

  md += `## Summary\n\n`;
  md += `| Metric | Count |\n`;
  md += `|--------|-------|\n`;
  md += `| Total CVEs | ${result.total_vulnerabilities} |\n`;
  md += `| Reachable | ${result.reachable_vulnerabilities} |\n`;
  md += `| Not Reachable | ${result.total_vulnerabilities - result.reachable_vulnerabilities} |\n`;
  md += `| Risk Score | ${result.overall_risk_score}/100 |\n\n`;

  md += `## Reachable Vulnerabilities (Action Required)\n\n`;

  if (reachable.length === 0) {
    md += `✅ No reachable vulnerabilities found!\n\n`;
  } else {
    reachable.forEach((v) => {
      md += renderMarkdownVulnerability(v);
    });
  }

  md += `## Not Reachable Vulnerabilities\n\n`;

  if (notReachable.length === 0) {
    md += `No non-reachable vulnerabilities.\n\n`;
  } else {
    notReachable.forEach((v) => {
      md += renderMarkdownVulnerability(v);
    });
  }

  md += `## Next Steps\n\n`;
  md += `1. Review reachable vulnerabilities above\n`;
  md += `2. Prioritize by severity and effort estimate\n`;
  md += `3. Apply recommended patches or code changes\n`;
  md += `4. Re-run analysis to confirm remediation\n`;
  md += `5. Integrate VRA into CI/CD for continuous monitoring\n\n`;

  md += `---\n\n`;
  md += `_Report generated by VRA - Vulnerability Reachability Analyzer_\n`;
  md += `_${new Date().toLocaleString()}_\n`;

  return md;
}

function renderMarkdownVulnerability(vuln: any): string {
  let md = `### ${vuln.vulnerability.cve_id} - ${vuln.vulnerability.package}@${vuln.vulnerability.current_version}\n\n`;

  md += `**Severity:** ${vuln.vulnerability.severity} | **Confidence:** ${vuln.confidence}%\n\n`;

  md += `**Affected versions:** ${vuln.vulnerability.affected_versions.join(', ')}\n\n`;

  if (vuln.call_chain) {
    md += `**Call chain:** ${vuln.call_chain.entry_point} → ${vuln.call_chain.path.join(' → ')}\n\n`;
  }

  if (vuln.reason) {
    md += `**Reason:** ${vuln.reason}\n\n`;
  }

  md += `#### Remediation (${vuln.remediation.type})\n\n`;
  md += `${vuln.remediation.description}\n\n`;

  if (vuln.remediation.required_version) {
    md += `**Target version:** \`${vuln.remediation.required_version}\`\n\n`;
  }

  if (vuln.remediation.breaking_changes !== undefined) {
    md += `**Breaking changes:** ${vuln.remediation.breaking_changes ? 'Yes ⚠️' : 'No ✓'}\n\n`;
  }

  if (vuln.remediation.changes_needed && vuln.remediation.changes_needed.length > 0) {
    md += `**Code changes needed:**\n\n`;
    vuln.remediation.changes_needed.forEach((change: string) => {
      md += `- ${change}\n`;
    });
    md += `\n`;
  }

  if (vuln.remediation.action) {
    md += `**Action:**\n\n\`\`\`bash\n${vuln.remediation.action}\n\`\`\`\n\n`;
  }

  if (vuln.remediation.effort_estimate) {
    md += `**Effort:** ${vuln.remediation.effort_estimate}\n\n`;
  }

  if (vuln.remediation.notes) {
    md += `**Notes:** ${vuln.remediation.notes}\n\n`;
  }

  md += `---\n\n`;

  return md;
}
