import type { AnalysisResult } from '../../types/analysis-result.js';
import { epssLabel, epssSummaryLine, kevCatalogLine, kevLabel } from '../../adapters/report/threat_labels.js';

export interface RenderMeta {
  aiPowered: boolean;
  providerName?: string;
}

/** Escapes text from advisories/AI so it cannot inject links, images, HTML or table cells. */
function esc(value: unknown): string {
  return String(value ?? '')
    .replace(/[\\`*_{}[\]()#+!|~>]/g, '\\$&')
    .replace(/</g, '&lt;')
    .replace(/\r?\n/g, ' ');
}

/** A code fence longer than any backtick run inside the content. */
function codeBlock(content: string, lang = ''): string {
  const longest = Math.max(2, ...(content.match(/`+/g) ?? []).map(run => run.length));
  const fence = '`'.repeat(longest + 1);
  return `${fence}${lang}\n${content}\n${fence}`;
}

export function renderMarkdownReport(result: AnalysisResult, meta: RenderMeta): string {
  const reachable = result.results.filter((v) => v.is_reachable);
  const notReachable = result.results.filter((v) => !v.is_reachable);

  let md = `# VRA - Vulnerability Reachability Analysis Report\n\n`;

  if (meta.aiPowered && meta.providerName) {
    md += `_Powered by ${esc(meta.providerName)}_\n\n`;
  }

  md += `## Summary\n\n`;
  md += `| Metric | Count |\n`;
  md += `|--------|-------|\n`;
  md += `| Total CVEs | ${result.total_vulnerabilities} |\n`;
  md += `| Reachable | ${result.reachable_vulnerabilities} |\n`;
  md += `| Not Reachable | ${result.total_vulnerabilities - result.reachable_vulnerabilities} |\n`;
  md += `| Risk Score | ${result.overall_risk_score}/100 |\n\n`;

  const kevLine = kevCatalogLine(result);
  if (kevLine) md += `${esc(kevLine)}\n\n`;
  const epssLine = epssSummaryLine(result);
  if (epssLine) md += `${esc(epssLine)}\n\n`;

  md += `## Reachable Vulnerabilities (Action Required)\n\n`;

  if (reachable.length === 0) {
    md += `✅ No reachable vulnerabilities found!\n\n`;
  } else {
    reachable.forEach((v) => {
      md += renderMarkdownVulnerability(v, result);
    });
  }

  md += `## Not Reachable Vulnerabilities\n\n`;

  if (notReachable.length === 0) {
    md += `No non-reachable vulnerabilities.\n\n`;
  } else {
    notReachable.forEach((v) => {
      md += renderMarkdownVulnerability(v, result);
    });
  }

  md += `## Next Steps\n\n`;
  md += `1. Review reachable vulnerabilities above\n`;
  md += `2. Prioritize by severity and effort estimate\n`;
  md += `3. Apply recommended patches or code changes\n`;
  md += `4. Re-run analysis to confirm remediation\n`;
  md += `5. Integrate VRA into CI/CD for continuous monitoring\n\n`;

  md += `---\n\n`;
  md += `_Report generated by VRA - Vulnerability Reachability Analyzer_\n`;
  md += `_${new Date().toLocaleString()}_\n`;

  return md;
}

function renderMarkdownVulnerability(vuln: any, result: AnalysisResult): string {
  let md = `### ${esc(vuln.vulnerability.cve_id)} - ${esc(vuln.vulnerability.package)}@${esc(vuln.vulnerability.current_version)}\n\n`;

  md += `**Severity:** ${esc(vuln.vulnerability.severity)} | **Confidence:** ${esc(vuln.confidence)}%\n\n`;

  md += `**Affected versions:** ${esc(vuln.vulnerability.affected_versions.join(', '))}\n\n`;

  md += `**EPSS:** ${esc(epssLabel(vuln.vulnerability, result))}\n\n`;
  md += `**CISA KEV:** ${esc(kevLabel(vuln.vulnerability, result))}\n\n`;

  if (vuln.call_chain) {
    md += `**Call chain:** ${esc(vuln.call_chain.entry_point)} → ${esc(vuln.call_chain.path.join(' → '))}\n\n`;
  }

  if (vuln.reason) {
    md += `**Reason:** ${esc(vuln.reason)}\n\n`;
  }

  md += `#### Remediation (${esc(vuln.remediation.type)})\n\n`;
  md += `${esc(vuln.remediation.description)}\n\n`;

  if (vuln.remediation.required_version) {
    md += `**Target version:** ${esc(vuln.remediation.required_version)}\n\n`;
  }

  if (vuln.remediation.breaking_changes !== undefined) {
    md += `**Breaking changes:** ${vuln.remediation.breaking_changes ? 'Yes ⚠️' : 'No ✓'}\n\n`;
  }

  if (vuln.remediation.changes_needed && vuln.remediation.changes_needed.length > 0) {
    md += `**Code changes needed:**\n\n`;
    vuln.remediation.changes_needed.forEach((change: string) => {
      md += `- ${esc(change)}\n`;
    });
    md += `\n`;
  }

  if (vuln.remediation.action) {
    md += `**Action** (verify before running):\n\n${codeBlock(String(vuln.remediation.action), 'bash')}\n\n`;
  }

  if (vuln.remediation.effort_estimate) {
    md += `**Effort:** ${esc(vuln.remediation.effort_estimate)}\n\n`;
  }

  if (vuln.remediation.notes) {
    md += `**Notes:** ${esc(vuln.remediation.notes)}\n\n`;
  }

  md += `---\n\n`;

  return md;
}
